/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#994522",
        "on-primary-container": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fcf9f8",
        "on-tertiary-fixed-variant": "#683b23",
        "on-secondary-fixed": "#161e0f",
        "tertiary-fixed": "#ffdbcb",
        "surface-container-low": "#f6f3f2",
        "primary-fixed": "#ffdbce",
        "outline-variant": "#dbc1b8",
        "surface-container-high": "#eae7e7",
        "tertiary": "#845238",
        "on-surface": "#1c1b1b",
        "inverse-surface": "#313030",
        "primary-fixed-dim": "#ffb59a",
        "on-primary": "#ffffff",
        "surface-tint": "#994623",
        "secondary-fixed-dim": "#c0cab2",
        "surface-container-highest": "#e5e2e1",
        "surface": "#fcf9f8",
        "on-tertiary-container": "#0e0200",
        "outline": "#88726b",
        "on-surface-variant": "#55433c",
        "inverse-primary": "#ffb59a",
        "surface-variant": "#e5e2e1",
        "on-secondary-fixed-variant": "#404a37",
        "surface-container": "#f0eded",
        "on-error": "#ffffff",
        "on-primary-fixed": "#370e00",
        "surface-dim": "#dcd9d9",
        "on-error-container": "#93000a",
        "secondary": "#58624e",
        "secondary-fixed": "#dce6cd",
        "background": "#fcf9f8",
        "on-tertiary-fixed": "#331101",
        "on-background": "#1c1b1b",
        "on-primary-fixed-variant": "#7b2f0d",
        "tertiary-container": "#a06a4f",
        "primary-container": "#b85d38",
        "tertiary-fixed-dim": "#fab898",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "secondary-container": "#d9e3ca",
        "on-secondary-container": "#5c6652",
        "inverse-on-surface": "#f3f0ef",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin": "1.25rem",
        "space-md": "1rem",
        "margin-desktop": "3rem",
        "space-xl": "2.5rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem"
      },
      fontFamily: {
        "display": ["Epilogue", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-mobile": ["Epilogue", "sans-serif"],
        "headline-sm": ["Epilogue", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Epilogue", "sans-serif"],
        "headline-lg": ["Epilogue", "sans-serif"]
      },
      fontSize: {
        "display": ["44px", { "lineHeight": "52px", "letterSpacing": "-0.03em", "fontWeight": "500" }],
        "headline-md": ["22px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "display-mobile": ["34px", { "lineHeight": "42px", "letterSpacing": "-0.025em", "fontWeight": "500" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "-0.015em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
}
